### ISSUE TITLE
generated image mutates the "input" portion of the init image

### ISSUE THREAD

**Issue by zeke** [replicate/outpainter#5]
I would expect the existing part of the image to remain "untouched" but it's getting distorted in the output image. Maybe this is a matter of tweaking some of the input parameters to the model?

Input:

![BruceBorn1984](https://github.com/replicate/outpainter/assets/2289/d30d7cab-e653-48fe-8913-ac5f47366e77)

Output:

![out-0](https://github.com/replicate/outpainter/assets/2289/08f5addb-dc63-4916-b930-556d0ef435a9)

**Comment by Pwntus** [comment]
It's a trade off. The current way makes the blend smoother, while keeping the original image may create a visible seam.

I agree that we should put the original image back, we can do it in two ways:
1. Just overlay the original image (still in memory) on top. Con: if you download the resulting image you won't get the original image overlayed.
2. We actually create a new image using canvas and output it as a data URI. Con: it makes it harder to download the image via right click.

I'll go ahead and implement number 2.

**Comment by Pwntus** [comment]
Turns out right click > save as for data URLs is not a problem.

Input:
![245969357-d30d7cab-e653-48fe-8913-ac5f47366e77](https://github.com/replicate/outpainter/assets/854759/0933cdcc-27cf-4843-bd95-96d2853e9fc0)

Output:
![download](https://github.com/replicate/outpainter/assets/854759/4f2fd6d2-89f5-4e81-bf8a-6d58dc70f10f)

We can now see the "seam" a bit better. This sort of counters the effects of https://github.com/replicate/outpainter/issues/3 . However I think it's better to have it like this and avoid distorting the text.

**Comment by Pwntus** [comment]
> Maybe this is a matter of tweaking some of the input parameters to the model?

Fwiw the `strength`/`prompt_strength` parameter would be a prime candidate to tweak for this. It's a value between 0.0 and 1.0, where 1.0 corresponds to the full destruction of information in the init image. In other words; a higher `strength` value makes the diffusion process modify the initial image more. Why I'm writing this is that I just found out this parameter is missing for the model we're using, which makes me wonder why that is.

https://replicate.com/cjwbw/stable-diffusion-v2-inpainting

**Comment by Pwntus** [comment]
Follow up: I actually think I solved the "seam" problem by just re-cropping the overlayed image and exposing the already inpainted seam:

Input:
![246090080-0933cdcc-27cf-4843-bd95-96d2853e9fc0](https://github.com/replicate/outpainter/assets/854759/11604bb1-467f-4afc-8f12-3612ae72218a)

Output:
![download](https://github.com/replicate/outpainter/assets/854759/76d292a2-d50d-47e4-a07c-5cf3086d27fa)

I had to reduce the mask overlap so that the text at the edges won't become distorted. Turns out you don't need a large overlap. A smaller overlap may though create a smooth but swift change in output content.

https://github.com/replicate/outpainter/blob/main/components/Outpainter.vue#L101

**Comment by Pwntus** [comment]
Input:
![outputtt](https://github.com/replicate/outpainter/assets/854759/8a0c45b4-a292-4ccc-8aef-243f984d63a8)


Output:
![download (1)](https://github.com/replicate/outpainter/assets/854759/e17a4450-dcf5-43d3-ac68-fa35bc5c71c9)

**Comment by Pwntus** [comment]
This is so fun.

Input:
![Screenshot 2023-06-15 at 18 06 39](https://github.com/replicate/outpainter/assets/854759/b4185452-cdc8-494f-821f-518b2efb007b)

Output:
![download (2)](https://github.com/replicate/outpainter/assets/854759/251891cf-38d0-48de-b87d-efdbc48f2820)

**Comment by zeke** [comment]
Love it!
